/**
 * Builds road segments for West Seattle → I-90 East → WA-26 → US-195 →
 * WSU (Pullman). All within Washington state.
 * Curves and hills use real GPS/elevation data from routeGeo.json when available
 * (generated by running: node fetchRoute.js).
 * Falls back to procedural generation when real data is absent.
 */
import { ROUTE_SEGS, SEG_LENGTH, TOTAL_ROUTE_MILES, REST_STOPS, CHECKPOINTS } from '../constants.js';
import { REGION_ORDER }           from '../utils/Colors.js';
import { SeededRNG, clamp }       from '../utils/Helpers.js';
import geoData                    from './routeGeo.json';

// Split flags so we can ship real curvature data without forcing real
// elevation data (or vice versa) — empty arrays just fall back to the
// in-code keyframe path for that channel.
const HAS_REAL_CURVES = !!geoData?.curves?.length && geoData.curves.length >= 100;
const HAS_REAL_HILLS  = !!geoData?.hills?.length  && geoData.hills.length  >= 100;
const HAS_REAL_GEO    = HAS_REAL_CURVES || HAS_REAL_HILLS;  // legacy alias

// Signs are spawned separately at very low density — not in the normal scenery array.
const SIGN_DENSITY = 0.003; // ~1 sign every 333 segments

const REGION_TRAITS = {
  // I-90 corridor: West Seattle → Spokane. Each region's curves/hills/scenery
  // are tuned to roughly match what you'd see driving that stretch.
  seattle_urban: {
    // West Seattle — single-family homes, low-rise residential.
    // densities are per-segment; with 470k-segment route, even small
    // numbers add up to thousands of buildings in a region.
    curveMax: 0.006, hillMax: 25, roadScale: 0.95, lanes: 4,
    scenery:  ['tree'],
    sceneryDensity: 0.02, buildings: true, buildingDensity: 0.05,
    buildingStyle: 'home',
    drugDensity: 0.005,
  },
  downtown_seattle: {
    // I-5 / I-90 interchange downtown — towers spaced so each is readable.
    curveMax: 0.010, hillMax: 35, roadScale: 0.92, lanes: 4,
    scenery:  ['tree'],
    sceneryDensity: 0.005, buildings: true, buildingDensity: 0.08,
    buildingStyle: 'tower',
    drugDensity: 0.004,
  },
  lake_washington: {
    // Floating bridge — almost dead straight, NO scenery either side, hard
    // guardrails so the player physically can't drive into the water.
    // `water: true` flips the side-grass to lake water in Road.js and
    // clamps player.x in GameScene.
    curveMax: 0.002, hillMax: 5, roadScale: 1.05, lanes: 4,
    scenery:  [],
    sceneryDensity: 0.0, buildings: false,
    drugDensity: 0.003,
    water: true,
  },
  mercer_island: {
    // Suburban island between the two floating bridges.  Single-family
    // homes, narrow tree-lined streets, no water.
    curveMax: 0.008, hillMax: 40, roadScale: 0.95, lanes: 4,
    scenery:  ['tree', 'tree'],
    sceneryDensity: 0.06, buildings: true, buildingDensity: 0.18,
    buildingStyle: 'home',
    drugDensity: 0.004,
  },
  eastside_urban: {
    // Bellevue downtown — 2 mi after the East Channel bridge.  Mid-rise
    // towers and office blocks, then transitions back to suburbs.
    curveMax: 0.008, hillMax: 30, roadScale: 0.96, lanes: 4,
    scenery: ['tree'],
    sceneryDensity: 0.02, buildings: true, buildingDensity: 0.18,
    buildingStyle: 'tower',
    drugDensity: 0.005,
  },
  eastside: {
    // Mercer Is → Bellevue → Issaquah → North Bend. Forested suburbs,
    // gentle hills as you climb out of the valley.
    curveMax: 0.012, hillMax: 100, roadScale: 1.00, lanes: 4,
    scenery:  ['tree', 'tree'],
    sceneryDensity: 0.07, buildings: true, buildingDensity: 0.30,
    drugDensity: 0.005,
  },
  cascades: {
    // North Bend → Snoqualmie Pass summit (3,022 ft) → Cle Elum.
    // The signature stretch: heavy switchbacks and the steepest grades on the route.
    curveMax: 0.024, hillMax: 360, roadScale: 0.85, lanes: 4,
    scenery:  ['tree', 'tree', 'tree'],
    sceneryDensity: 0.10, buildings: false,
    drugDensity: 0.004,
  },
  east_cascades: {
    // Cle Elum → Ellensburg → Vantage. Drier evergreens, descending into
    // the Yakima River valley with a final climb to the Columbia plateau.
    curveMax: 0.014, hillMax: 200, roadScale: 1.00, lanes: 4,
    scenery:  ['tree'],
    sceneryDensity: 0.05, buildings: false,
    drugDensity: 0.005,
  },
  columbia_basin: {
    // Vantage → Moses Lake → Ritzville. High desert, sagebrush, mostly
    // straight and flat across the basin.  Mix of low shrubs (sagebrush)
    // with the occasional scrub pine — no cactus (none of those grow
    // in the Columbia Basin).
    curveMax: 0.005, hillMax: 60, roadScale: 1.20, lanes: 4,
    scenery:  ['shrub', 'shrub', 'shrub', 'tree'],
    sceneryDensity: 0.03, buildings: false,
    drugDensity: 0.006,
  },
  palouse: {
    // Ritzville → Colfax → WSU. Rolling Palouse wheat country with
    // occasional small farm towns and finally WSU on the hills.
    curveMax: 0.009, hillMax: 130, roadScale: 1.05, lanes: 4,
    scenery:  ['tree'],
    sceneryDensity: 0.012, buildings: true, buildingDensity: 0.02,
    buildingStyle: 'home',
    drugDensity: 0.005,
  },
};

// Realistic-but-readable building palettes per style.
const TOWER_COLORS = [
  0x5C6A78,  0x4A5B6B,  0x6F7E8C,  0x3D4754,    // slate / glass-blue
  0x8A9AA8,  0x6E6B65,  0x8C8A86,  0xA8A299,    // concrete
];
const HOUSE_COLORS = [
  0xC8B89A,  0xB89A78,  0xD6C8A8,  0xA88A66,    // cream / tan / wood
  0xC0B6A8,  0x8E7A60,  0xD8B888,  0xB8A088,    // weathered wood / stucco
  0xE0D4B8,  0xA89880,                           // pale beige
];
const ROOF_COLORS  = [
  0x4A2E2A,  0x5A3835,  0x3A2825,  0x6E4540,    // shingle browns/dark reds
  0x4D4A45,  0x3A3B3D,                           // grey shingle
];

function getTraitsAt(t) {
  for (const r of REGION_ORDER) {
    if (t >= r.start && t < r.end) return REGION_TRAITS[r.key];
  }
  // Fallback to last region (covers t === 1.0 edge case + any out-of-range t).
  const last = REGION_ORDER[REGION_ORDER.length - 1];
  return REGION_TRAITS[last.key];
}

function smooth(arr, strength = 0.15) {
  const result = [...arr];
  for (let i = 1; i < arr.length; i++) {
    result[i] = result[i - 1] * (1 - strength) + arr[i] * strength;
  }
  return result;
}

// Centered box-blur — symmetric, no forward bias.  Apply multiple passes
// for a Gaussian-like response (3 passes ≈ Gaussian).  Used on hills[]
// so the elevation profile is smoother than what smoothstep keyframes
// give us by themselves (smoothstep has slope=0 at every keyframe, which
// stacks micro-humps when keyframes are tightly spaced).
function boxBlurCentered(arr, halfWidth, passes = 1) {
  let src = arr;
  for (let p = 0; p < passes; p++) {
    const n = src.length;
    const dst = new Array(n);
    let sum = 0;
    let count = 0;
    // Prime the window over [0, halfWidth]
    for (let j = 0; j <= Math.min(halfWidth, n - 1); j++) {
      sum += src[j];
      count++;
    }
    for (let i = 0; i < n; i++) {
      dst[i] = sum / count;
      const addIdx = i + halfWidth + 1;
      const dropIdx = i - halfWidth;
      if (addIdx < n) { sum += src[addIdx]; count++; }
      if (dropIdx >= 0) { sum -= src[dropIdx]; count--; }
    }
    src = dst;
  }
  return src;
}

// Interpolate a sampled array at progress t (0–1)
function sampleArr(arr, t) {
  const idx = t * (arr.length - 1);
  const lo  = Math.floor(idx);
  const hi  = Math.min(lo + 1, arr.length - 1);
  return arr[lo] + (arr[hi] - arr[lo]) * (idx - lo);
}

// Helper used by the tunnel-tagging block down below.  Inline rather than
// reaching for the SEGS_PER_MILE that's only defined later in the random-
// roadside-cop pass.
const SEGS_PER_MILE_FOR_TUNNEL = (count) => count / TOTAL_ROUTE_MILES;

export function buildRoute(count = ROUTE_SEGS) {
  const rng      = new SeededRNG(1337);
  const segments = [];

  // ── Curves ───────────────────────────────────────────────────────────
  const rawCurves = new Array(count).fill(0).map((_, i) => {
    const t      = i / count;
    const traits = getTraitsAt(t);
    if (HAS_REAL_CURVES) {
      // Real road curvature from hand-keyframed I-90 data, lightly blended
      // with per-region noise so the road still feels organic.
      const real  = clamp(sampleArr(geoData.curves, t), -0.022, 0.022);
      const noise = rng.range(-traits.curveMax * 0.25, traits.curveMax * 0.25);
      return real + noise;
    }
    const noise = rng.range(-traits.curveMax, traits.curveMax);
    const wave  = Math.sin(i * 0.003) * traits.curveMax * 0.7;
    return noise * 0.4 + wave * 0.6;
  });
  // ── Manual curve overrides ────────────────────────────────────────
  // Real I-90 has a noticeable LEFT bend coming off the Lacey Murrow
  // bridge onto Mercer Island and a RIGHT bend exiting the Mercer
  // Island Lid Tunnel.  Add a curve impulse over those mile windows so
  // the road plays like the real route.  Each impulse is shaped as a
  // half-sine across the window so the curve eases in and out.
  const addCurveImpulse = (mileStart, mileEnd, peakCurve) => {
    const i0 = Math.floor((mileStart / TOTAL_ROUTE_MILES) * count);
    const i1 = Math.floor((mileEnd   / TOTAL_ROUTE_MILES) * count);
    for (let i = i0; i < i1; i++) {
      const tt = (i - i0) / Math.max(1, i1 - i0);
      rawCurves[i] = (rawCurves[i] ?? 0) + peakCurve * Math.sin(tt * Math.PI);
    }
  };
  // Bridge stays straight from 7.0–8.0 — no curve there.  Left bend
  // begins ONLY after the player rolls off the bridge onto Mercer
  // Island at mile 8.0, easing back to neutral by 8.5 (lid-tunnel
  // entrance).  Right bend after the lid tunnel exits.
  addCurveImpulse(8.0, 8.5, -0.012);   // Onto Mercer Island — left bend
  addCurveImpulse(9.0, 9.6, +0.010);   // Lid-tunnel exit — right bend
  const curves = smooth(rawCurves, 0.04);

  // ── Hills ────────────────────────────────────────────────────────────
  // Real-world I-90 / WA-26 / US-195 elevation profile from authoritative
  // sources (USGS, WSDOT, Wikipedia per-town elevations).  39 keyframes
  // capture every major topographic landmark on the 293-mi drive: the
  // hilltop start in West Seattle, the Duwamish descent to sea level,
  // the floating-bridge water crossing, the Mt. Baker tunnel, the climb
  // up the Cascades to Snoqualmie Pass (3022 ft), the Yakima River
  // canyon dip, Indian John Hill, Elk Heights, the dramatic
  // Ryegrass-Summit→Vantage drop into the Columbia gorge (~1965 ft over
  // 10 mi), the scabland coulees, and the rolling Palouse climb to
  // Pullman.  t = mile / 293.
  const I90_ELEV_FT = [
    [0.0000,   350],   //   0 mi:  West Seattle (Alaska Junction hilltop)
    [0.0068,   200],   //   2 mi:  West Seattle Bridge midspan (high above Duwamish)
    [0.0102,    20],   //   3 mi:  Off the bridge into SoDo (sea level)
    [0.0170,    20],   //   5 mi:  SoDo (still sea level)
    [0.0205,    55],   //   6 mi:  Mt. Baker Tunnel west portal
    [0.0228,    55],   //   6.7 mi: Mt. Baker Tunnel east portal
    [0.0240,    25],   //   7.0 mi: Coming off the tunnel ramp toward bridge (eased)
    [0.0252,    20],   //   7.4 mi: Floating bridge midspan — water level
    [0.0273,    20],   //   8 mi:  Bridge end / Mercer Island west shore (still water level)
    [0.0280,    34],   //   8.2 mi: Gentle ramp up off the bridge (eased so NPCs don't pop)
    [0.0288,    60],   //   8.4 mi: Steeper climb up the Mercer Island ridge
    [0.0294,    78],   //   8.6 mi: Approach to Mercer Island Lid Tunnel
    [0.0303,    78],   //   8.9 mi: Inside the lid tunnel — held flat
    [0.0312,    72],   //   9.1 mi: Just past lid tunnel exit
    [0.0325,    50],   //   9.5 mi: Gentle descent toward East Channel
    [0.0341,    25],   //  10 mi:  East Channel Bridge approach (lake level)
    [0.0392,    32],   //  11.5 mi: East Channel Bridge end — Bellevue shore
    [0.0410,    92],   //  12 mi:  Bellevue (I-405 jct, climbing up)
    [0.0512,   200],   //  15 mi:  Eastgate climb
    [0.0580,   108],   //  17 mi:  Issaquah (valley floor)
    [0.0751,   450],   //  22 mi:  Preston / Tiger Mountain shoulder
    [0.0956,   420],   //  28 mi:  Snoqualmie / Fall City exit
    [0.1092,   525],   //  32 mi:  North Bend
    [0.1297,   900],   //  38 mi:  South Fork Snoqualmie (climb begins)
    [0.1536,  2000],   //  45 mi:  Denny Creek / Asahel Curtis
    [0.1706,  2600],   //  50 mi:  Hyak / Keechelus Lake west shore
    [0.1775,  3022],   //  52 mi:  SNOQUALMIE PASS SUMMIT
    [0.1877,  2650],   //  55 mi:  Hyak east / Keechelus Dam
    [0.2116,  2180],   //  62 mi:  Easton
    [0.2389,  2050],   //  70 mi:  Cabin Creek
    [0.2662,  1906],   //  78 mi:  Cle Elum
    [0.2901,  1950],   //  85 mi:  Thorp
    [0.3038,  2141],   //  89 mi:  Indian John Hill summit (rest area)
    [0.3413,  1600],   // 100 mi:  Yakima River canyon descent
    [0.3584,  1535],   // 105 mi:  Ellensburg (I-82 jct)
    [0.3925,  2359],   // 115 mi:  Elk Heights
    [0.4164,  2535],   // 122 mi:  Ryegrass Summit (highest east of pass)
    [0.4505,   570],   // 132 mi:  VANTAGE BRIDGE / Columbia River (lowest east)
    [0.4573,   900],   // 134 mi:  Climb out of river canyon (WA-26 begins)
    [0.4778,  1000],   // 140 mi:  Sand Hollow / Royal Slope
    [0.5119,  1027],   // 150 mi:  Royal City
    [0.5631,  1050],   // 165 mi:  Frenchman Hills crossing
    [0.6143,  1060],   // 180 mi:  Othello
    [0.6826,  1250],   // 200 mi:  Hatton Coulee plateau
    [0.7679,  1027],   // 225 mi:  Washtucna (in coulee floor)
    [0.8191,  1400],   // 240 mi:  Climb out of Washtucna Coulee
    [0.8532,  1475],   // 250 mi:  La Crosse
    [0.9044,  1800],   // 265 mi:  Dusty / Palouse rolling hills
    [0.9454,  1965],   // 277 mi:  Colfax (US-195 jct)
    [0.9727,  2400],   // 285 mi:  Climb up Palouse ridge
    [1.0000,  2352],   // 293 mi:  PULLMAN (WSU)
  ];
  // Catmull-Rom interpolation between keyframes — gives a globally
  // C1-continuous elevation curve (the slope at each keyframe matches
  // the chord between its neighbors instead of being forced to zero).
  // Smoothstep gave slope=0 at every keyframe, which stacked a tiny
  // "wave" into each span and made the road feel bumpy when keyframes
  // were closely spaced (Mercer Island, North Bend descent, the tunnels).
  const elevAt = (t) => {
    const kf = I90_ELEV_FT;
    const n  = kf.length;
    if (t <= kf[0][0])     return kf[0][1];
    if (t >= kf[n - 1][0]) return kf[n - 1][1];
    let i = 0;
    for (; i < n - 1; i++) if (t <= kf[i + 1][0]) break;
    const p0 = kf[Math.max(0, i - 1)][1];
    const p1 = kf[i][1];
    const p2 = kf[i + 1][1];
    const p3 = kf[Math.min(n - 1, i + 2)][1];
    const span = kf[i + 1][0] - kf[i][0];
    const u    = span > 0 ? (t - kf[i][0]) / span : 0;
    const u2   = u * u;
    const u3   = u2 * u;
    // Catmull-Rom matrix, tension = 0.5.
    return 0.5 * (
      (2 * p1) +
      (-p0 + p2) * u +
      (2 * p0 - 5 * p1 + 4 * p2 - p3) * u2 +
      (-p0 + 3 * p1 - 3 * p2 + p3) * u3
    );
  };

  // World elevation is absolute, not an accumulated random walk. Keep the
  // pavement profile clean and macro-scale: the real-route keyframes create
  // the climbs and descents, while the road surface itself stays smooth.
  const ELEV_SCALE = 340;
  const baseElevFt = elevAt(0);
  const rawHills = new Array(count).fill(0).map((_, i) => {
    const t = i / count;
    if (HAS_REAL_HILLS) {
      return sampleArr(geoData.hills, t) * ELEV_SCALE;
    }
    return (elevAt(t) - baseElevFt) * ELEV_SCALE;
  });
  // Smooth hills[] so the road profile is C2-smooth.  The window has to
  // be WIDER than the keyframe spacing in dense areas (Mercer Island
  // keyframes range 280-610 segs apart) to flatten the keyframe-induced
  // waviness at all.  halfWidth=400 (window=801 segs ≈ 0.5 mi) with 3
  // passes spans 2-3 adjacent keyframes in those dense zones, killing
  // the wave pattern.  Macro features (Snoqualmie 50+ mi, Vantage 10 mi)
  // are far wider than the smoothing window so they survive intact.
  const hills = boxBlurCentered(rawHills, 400, 3);

  // ── Road scale (gradual region-to-region width transition) ───────────
  const rawScales  = new Array(count).fill(1).map((_, i) => getTraitsAt(i / count).roadScale);
  const roadScales = smooth(rawScales, 0.008);

  // Per-segment macro grade — re-derive from the SMOOTHED hills[] (not
  // the raw keyframe elevAt) so grade matches what the renderer actually
  // draws.  Used by the camera pitch lookahead and steep-grade signage.
  const macroGrade   = new Array(count);
  const realGradePct = new Array(count);
  const ftPerSeg = (1 / count) * TOTAL_ROUTE_MILES * 5280;
  for (let i = 0; i < count; i++) {
    const a = hills[i];
    const b = hills[Math.min(count - 1, i + 1)];
    const dY = b - a;                                          // world units
    macroGrade[i]   = dY / SEG_LENGTH;                          // world Y / seg
    realGradePct[i] = ftPerSeg > 0 ? (dY / ELEV_SCALE) / ftPerSeg : 0;
  }
  // Extra polish — symmetric box pass on the grade arrays so signage /
  // physics see a clean curve even where hills[] still has tiny ripples.
  const macroGradeSmooth   = boxBlurCentered(macroGrade,   12, 2);
  const realGradePctSmooth = boxBlurCentered(realGradePct, 12, 2);

  for (let i = 0; i < count; i++) {
    const t      = i / count;
    const traits = getTraitsAt(t);

    const sprites = [];

    // ── Natural scenery ───────────────────────────────────────────────
    // Two-band placement for depth:
    //   • CLOSE band (offset 1.18–1.55) — most common; sits about a lane's
    //     distance from the fog line so the player drives past dense trees.
    //   • FAR  band (offset 1.9–4.5) — spread further out into the scene
    //     so the world has perceived depth instead of a 2-deep tree wall.
    // Each segment can spawn from either band on either side independently.
    const TREE_TEXTURES = ['tree_hemlock1', 'tree_hemlock2', 'tree_cedar1', 'tree_cedar2', 'tree_generic'];
    const pickTreeTex = () => TREE_TEXTURES[Math.floor(rng.next() * TREE_TEXTURES.length)];
    const pushTree = (offset) => {
      const type = rng.pick(traits.scenery);
      sprites.push({
        type,
        texKey: type === 'tree' ? pickTreeTex() : null,
        offset,
        baseW: 2000, baseH: 7000,
        collected: false,
      });
    };
    if (traits.scenery.length > 0) {
      // Inner band (offset 1.6–2.05) — sits ~1 lane back from the fog line
      // so the player has a grass shoulder to spin out into instead of
      // immediately slamming a tree. The user explicitly wants this buffer
      // since trees are a crash hazard.
      const innerP = traits.sceneryDensity * 1.4;
      if (rng.bool(innerP)) pushTree( rng.range(1.6, 2.05));
      if (rng.bool(innerP)) pushTree(-rng.range(1.6, 2.05));
      // Outer band — fills the scenery scene to the horizon at slightly
      // higher per-segment probability so the world has visible depth.
      const outerP = traits.sceneryDensity * 2.2;
      if (rng.bool(outerP)) pushTree( rng.range(2.3, 5.0));
      if (rng.bool(outerP)) pushTree(-rng.range(2.3, 5.0));
    }

    // (Random brown freeway signs removed — real mileage signs are
    // placed below at each CHECKPOINT location.)

    // ── Buildings (urban regions) ─────────────────────────────────────
    // Two-band placement so cities have depth:
    //   • Frontage band (offset 2.35–3.15) — set back from the sidewalk
    //     by roughly a player-car width so houses do not visually hang
    //     into the roadway at close projection.
    //   • Block-deep band (offset 3.2–5.6) — buildings further into the
    //     city block. Spawns more often than frontage to fill the scene.
    // Generic procedural-style fallback pool (used for regions without a
    // dedicated photo asset set, e.g. palouse).
    const BUILDING_TEXTURES = ['building_1','building_2','building_3','building_4','building_5','building_6','building_7'];
    // Region-specific photo pools — user-supplied "Scene Building" assets.
    //   • West Seattle homes — single-family residences (Pacific NW).
    //   • Sea/Bev skyscrapers — downtown Seattle + downtown Bellevue cores.
    //   • Bell/Issy mid-rise — Bellevue surroundings + Issaquah corridor.
    const WEST_SEATTLE_HOMES = ['west_seattle_1','west_seattle_2','west_seattle_3','west_seattle_4','west_seattle_5','west_seattle_6'];
    const SEA_BEV_TOWERS     = ['sea_bev_1','sea_bev_2','sea_bev_3','sea_bev_4','sea_bev_5','sea_bev_6'];
    const BELL_ISSY_BLDG     = ['bell_issy_1','bell_issy_2','bell_issy_3','bell_issy_4','bell_issy_5','bell_issy_6'];
    // Resolve the right pool for the current segment based on which
    // I-90 region we're in.  Eastside (post-Bellevue) flips to West
    // Seattle homes for the Issaquah tail (mile 16+) so that exit reads
    // as the residential edge of town, per user direction.
    const _mileForPool = t * TOTAL_ROUTE_MILES;
    let _regionKeyForPool = null;
    for (const r of REGION_ORDER) {
      if (t >= r.start && t < r.end) { _regionKeyForPool = r.key; break; }
    }
    const buildingPool = (() => {
      switch (_regionKeyForPool) {
        case 'seattle_urban':
        case 'mercer_island':   return WEST_SEATTLE_HOMES;
        case 'downtown_seattle':return SEA_BEV_TOWERS;
        case 'eastside_urban':  return rng.bool(0.55) ? SEA_BEV_TOWERS : BELL_ISSY_BLDG;
        case 'eastside':        return _mileForPool >= 16 ? WEST_SEATTLE_HOMES : BELL_ISSY_BLDG;
        default:                return BUILDING_TEXTURES;
      }
    })();
    // Treat a homes-only pool as a residential context — the spawner
    // skips procedural houses and drops in image-based homes instead.
    const poolIsHomes = buildingPool === WEST_SEATTLE_HOMES;
    // Block-based texture picker — neighbours share a primary style for
    // ~40-segment runs (≈ a city block) so the eye reads coherent
    // neighbourhoods of similar homes instead of one-of-each chaos.
    // Each block has a "primary" key picked by index; 70 % of buildings
    // in the block use it, 30 % drift to a random other key for variety.
    const pickBuildingTex = () => {
      const block      = Math.floor(i / 40);
      const primary    = buildingPool[(block * 7 + 3) % buildingPool.length];
      return rng.bool(0.70)
        ? primary
        : buildingPool[Math.floor(rng.next() * buildingPool.length)];
    };
    const makeBuilding = (offset, style) => {
      // Photo-home regions (West Seattle, Mercer Island, Issaquah tail)
      // always spawn image-based residences regardless of the region's
      // declared style — the West Seattle photos are wide-short homes, not
      // towers, so their geometry needs to match.
      if (poolIsHomes) {
        return {
          type:      'building',
          texKey:    pickBuildingTex(),
          offset,
          // Home photos are roughly 1.4× wider than tall — slightly bigger
          // than the procedural-house footprint so they read at full size
          // when the camera is close.
          baseW:     5400 + Math.floor(rng.next() * 2400),
          baseH:     4200 + Math.floor(rng.next() * 1400),
          collected: false,
        };
      }
      if (style === 'home') {
        return {
          type:      'house',
          offset,
          // 1.5× wider, 2/3 height vs the previous 5× pass — houses
          // now read as wider/shorter ranches/two-stories instead of
          // tall narrow towers.
          baseW:     5200 + Math.floor(rng.next() * 2600),
          baseH:     4600 + Math.floor(rng.next() * 1600),
          wallColor: HOUSE_COLORS[Math.floor(rng.next() * HOUSE_COLORS.length)],
          roofColor: ROOF_COLORS[Math.floor(rng.next() * ROOF_COLORS.length)],
          // Per-house shape rolls.  flatRoof gives modern/contemporary
          // homes a flat roofline instead of the gabled default.
          variant:   rng.next(),
          flatRoof:  rng.bool(0.40),
          hasGarage: rng.bool(0.55),
          hasChimney:rng.bool(0.40),
          hasDormer: rng.bool(0.30),
          twoStory:  rng.bool(0.45),
          collected: false,
        };
      }
      const isTower = style === 'tower';
      const bFloors = isTower
        ? 6 + Math.floor(rng.next() * 12)
        : 3 + Math.floor(rng.next() * 4);
      return {
        type:      'building',
        texKey:    pickBuildingTex(),
        offset,
        baseW:     isTower
          ? 900 + Math.floor(rng.next() * 700)
          : 700 + Math.floor(rng.next() * 500),
        baseH:     2200 + bFloors * 1100,
        wallColor: TOWER_COLORS[Math.floor(rng.next() * TOWER_COLORS.length)],
        floors:    bFloors,
        collected: false,
      };
    };
    // Hard cap: no buildings past mile 17 (Issaquah onward).  Player
    // wants the suburbs/cities to taper out into open road from there.
    // Bellevue tail (mile 14-17) — Bellevue's east half is mostly
    // wooded foothill leading into Issaquah; thin out density so the
    // city dissolves naturally rather than ending abruptly at mile 17.
    const mileNow = t * TOTAL_ROUTE_MILES;
    let densityScale = 1.0;
    if (mileNow > 14 && mileNow <= 17) {
      // Linear taper 1.0 → 0.15 over miles 14-17.
      densityScale = 1.0 - 0.85 * ((mileNow - 14) / 3);
    }
    if (traits.buildings && mileNow <= 17) {
      const style = traits.buildingStyle || 'midrise';
      if (poolIsHomes) {
        // ── Neighborhood-block placement ────────────────────────────
        // Homes don't read as "a neighborhood" when each segment rolls
        // independently — you get a sprinkle of houses with random gaps.
        // Group them into ~50-segment blocks (≈ a real residential block)
        // where 70% of blocks are dense rows of homes and 30% are gaps
        // (parks / cul-de-sacs / vacant lots).  Within a block, both
        // sides share roughly the same setback so homes line up like a
        // planned subdivision instead of zig-zagging.
        const block        = Math.floor(i / 50);
        const blockHash    = (block * 7919 + 13) % 100;
        const blockHasHomes= blockHash < 70;
        const blockMul     = blockHasHomes ? 1.6 : 0.10;
        const blockSetback = 2.45 + ((block * 1117 + 5) % 60) / 100;  // 2.45–3.05
        const jitter       = () => (rng.next() - 0.5) * 0.12;
        const frontP       = traits.buildingDensity * 0.30 * densityScale * blockMul;
        if (rng.bool(frontP)) sprites.push(makeBuilding( blockSetback + jitter(), style));
        if (rng.bool(frontP)) sprites.push(makeBuilding(-blockSetback + jitter(), style));
        // Second-row homes — typical of a subdivision with parallel
        // streets behind the frontage.  Half the rate so the back row
        // reads as sparser depth fill, not a doubled wall.
        const deepP = traits.buildingDensity * 0.35 * densityScale * blockMul;
        if (rng.bool(deepP)) sprites.push(makeBuilding( blockSetback + 1.4 + jitter(), style));
        if (rng.bool(deepP)) sprites.push(makeBuilding(-blockSetback - 1.4 + jitter(), style));
        // Far-back row — homes way out at the edge of perception.  Cheap
        // pseudo-3D depth: each segment is just a few extra rng.bool()
        // rolls + sprite slots, no per-frame cost.  Quarter rate so the
        // distance reads as dotted houses on the horizon, not another wall.
        const backP = traits.buildingDensity * 0.18 * densityScale * blockMul;
        if (rng.bool(backP)) sprites.push(makeBuilding( blockSetback + 3.0 + jitter(), style));
        if (rng.bool(backP)) sprites.push(makeBuilding(-blockSetback - 3.0 + jitter(), style));
      } else {
        // Original generic placement — used by tower / midrise regions.
        const frontageP = traits.buildingDensity * 0.30 * densityScale;
        if (rng.bool(frontageP)) sprites.push(makeBuilding( rng.range(2.35, 3.15), style));
        if (rng.bool(frontageP)) sprites.push(makeBuilding(-rng.range(2.35, 3.15), style));
        const deepP = traits.buildingDensity * 0.70 * densityScale;
        if (rng.bool(deepP)) sprites.push(makeBuilding( rng.range(3.2, 5.6), style));
        if (rng.bool(deepP)) sprites.push(makeBuilding(-rng.range(3.2, 5.6), style));
      }
    }
    // ── Drug collectibles (density varies by region) ─────────────────
    // type starts as 'drug-pending' so the actual drug is chosen at runtime
    // by DrugSystem.chooseAddictedDrug(...) when the sprite enters the visible
    // window. That lets per-player addiction skew which drug actually shows up.
    if (rng.bool(traits.drugDensity ?? 0.020)) {
      sprites.push({
        type:            'drug-pending',
        defaultType:     pickCollectible(rng, t),
        offset:          rng.range(-0.55, 0.55),
        baseW: 720, baseH: 880,   // 2× per request — much easier to spot
        collected:       false,
        isCollectible:   true,
        collectibleType: 'drug',
        // Stable per-sprite roll so 4★+ suppression (~40% of drugs disappear)
        // is deterministic — same spot suppressed every time the player
        // re-enters that segment at high heat.
        lootSeed:        rng.next(),
      });
    }

    // ── F12 weapon tokens ─────────────────────────────────────────────
    // Spaced ~every 1,200 segments (≈ 9 sec at top speed) so they're
    // tactical pickups, not spam.
    if (i % 1200 === 77) {
      const f12Type = pickF12(rng);
      const f12TexMap = {
        f12_gun:    'weapon_gun',
        f12_spike:  'weapon_spike_strip',
        f12_paint:  'weapon_paint_bomb',
        f12_rocket: 'weapon_rocket',     // procedural placeholder if PNG missing
      };
      sprites.push({
        type:            f12Type,
        texKey:          f12TexMap[f12Type],
        offset:          rng.range(-0.45, 0.45),
        baseW: 720, baseH: 880,   // same as drug pickups so they appear similar size
        collected:       false,
        isCollectible:   true,
        collectibleType: 'f12',
      });
    }

    // ── Cop roadblock ─────────────────────────────────────────────────
    if (i > 300 && i % 240 === 133 && t > 0.05) {
      sprites.push({
        type:            'cop_roadblock',
        offset:          (rng.bool() ? 0.12 : -0.12),
        baseW: 800, baseH: 420,  // big and unmissable
        collected:       false,
        isCollectible:   true,
        collectibleType: 'cop_roadblock',
      });
    }

    // ── Hitchhiker ────────────────────────────────────────────────────
    if (rng.bool(0.006)) {
      sprites.push({
        type:            'hitchhiker',
        offset:          rng.range(-0.9, -0.75),
        baseW:  80, baseH: 200,
        collected:       false,
        isCollectible:   true,
        collectibleType: 'hitchhiker',
      });
    }

    segments.push({
      index:     i,
      y:         hills[i],
      curve:     curves[i],
      grade:     macroGradeSmooth[i],     // world-Y rise per SEG_LENGTH
      gradePct:  realGradePctSmooth[i],   // real-world grade fraction (0.06 = 6%)
      lanes:     traits.lanes,
      roadScale: roadScales[i],
      urban:     !!traits.buildings,   // drives sidewalk drawing in Road.js
      water:     !!traits.water,        // drives bridge guardrails + water tile
      sprites,
      cars: [],
    });
  }

  // ── Mt Baker Tunnel (mile 6.0–7.0) ─────────────────────────────────────
  // West portal at the SoDo end of I-90, east portal opens onto the
  // Lacey V. Murrow Floating Bridge approach.  Concrete walls + ceiling
  // + roadside scenery stripped.
  {
    const ts = Math.floor(6.0 * SEGS_PER_MILE_FOR_TUNNEL(count)) % count;
    const te = Math.floor(7.0 * SEGS_PER_MILE_FOR_TUNNEL(count)) % count;
    for (let i = ts; i !== te; i = (i + 1) % count) {
      const seg = segments[i];
      if (!seg) continue;
      seg.tunnel = true;
      if (seg.sprites?.length) {
        seg.sprites = seg.sprites.filter(sp => sp.isCollectible);
      }
    }
  }

  // ── Mercer Island Lid Tunnel (mile 8.5–9.0) ───────────────────────────
  // After the floating bridge climbs onto Mercer Island, I-90 cuts
  // through a covered "lid" structure across the island ridge.  Treated
  // identically to the Mt Baker tunnel — concrete walls + ceiling.
  // IMPORTANT: this falls inside the lake_washington region, which sets
  // seg.water = true via traits.  We clear that flag on tunnel segments
  // so the water tile doesn't paint through the tunnel floor.
  {
    const ts = Math.floor(8.5 * SEGS_PER_MILE_FOR_TUNNEL(count)) % count;
    const te = Math.floor(9.0 * SEGS_PER_MILE_FOR_TUNNEL(count)) % count;
    for (let i = ts; i !== te; i = (i + 1) % count) {
      const seg = segments[i];
      if (!seg) continue;
      seg.tunnel = true;
      seg.water  = false;
      if (seg.sprites?.length) {
        seg.sprites = seg.sprites.filter(sp => sp.isCollectible);
      }
    }
  }

  // ── West Seattle Bridge ──────────────────────────────────────────────
  // Mile 2.0 → 3.0 — the high concrete bridge over the Duwamish.  Tagged
  // segments get drivable bridge rendering (deck + railings + pylons +
  // water far below) and a hard rail clamp like the tunnel walls.
  // Strip roadside scenery (trees / buildings) — you're 200 ft up over
  // the river, nothing should be at road level.
  const bridgeStart = Math.floor(2.0 * SEGS_PER_MILE_FOR_TUNNEL(count)) % count;
  const bridgeEnd   = Math.floor(3.0 * SEGS_PER_MILE_FOR_TUNNEL(count)) % count;
  for (let i = bridgeStart; i !== bridgeEnd; i = (i + 1) % count) {
    const seg = segments[i];
    if (!seg) continue;
    seg.bridge = true;
    if (seg.sprites?.length) {
      seg.sprites = seg.sprites.filter(sp => sp.isCollectible);
    }
  }

  // ── East Channel Bridge (Mercer Island → Bellevue) ───────────────────
  // Real-route mile 10.0 → 11.5: 1.5 miles of floating bridge over the
  // East Channel between Mercer Island and the Bellevue shore.  Same
  // render treatment as the Murrow (water tile + railings, no roadside
  // scenery).  The lake_washington region trait already sets
  // seg.water=true for this stretch via REGION_ORDER, but we tag the
  // bridge segments explicitly here for clarity / robustness.
  {
    const ts = Math.floor(10.0 * SEGS_PER_MILE_FOR_TUNNEL(count)) % count;
    const te = Math.floor(11.5 * SEGS_PER_MILE_FOR_TUNNEL(count)) % count;
    for (let i = ts; i !== te; i = (i + 1) % count) {
      const seg = segments[i];
      if (!seg) continue;
      seg.water = true;
      if (seg.sprites?.length) {
        seg.sprites = seg.sprites.filter(sp => sp.isCollectible);
      }
    }
  }

  // ── Random roadside cops — every 15–30 miles, 50/50 parked vs driving.
  //
  // Parked cops sit on the shoulder facing the road (left or right side
  // → uses car_left_police / car_right_police side-view art).  Driving
  // cops cruise in same-direction lanes alongside other traffic, using
  // the back-view police art.
  //
  // GameScene watches for the player passing one of these (with stars ≥ 1)
  // and converts the encounter into an active rear-pursuit cop.
  const SEGS_PER_MILE = count / TOTAL_ROUTE_MILES;
  let mile = 18 + rng.range(0, 12);                 // first cop at mile 18-30
  while (mile < TOTAL_ROUTE_MILES - 1) {
    const segIdx = Math.floor(mile * SEGS_PER_MILE) % count;
    const seg    = segments[segIdx];
    if (seg) {
      const parked   = rng.bool(0.5);
      const sideRight = rng.bool(0.5);
      seg.sprites.push({
        type:        parked ? 'cop_random_parked' : 'cop_random_driving',
        offset:      parked
          ? (sideRight ? rng.range(1.20, 1.45) : -rng.range(1.20, 1.45))  // shoulder
          : (rng.bool(0.5) ? 0.25 : 0.65),                                  // same-direction lane
        side:        parked ? (sideRight ? 'right' : 'left') : null,
        baseW:       parked ? 700 : 600,
        baseH:       parked ? 900 : 1000,
        collected:   false,
        copEncounter: true,                          // GameScene flag
        triggered:   false,
      });
    }
    mile += 15 + rng.range(0, 15);                  // next cop 15–30 mi later
  }

  // ── Rest-stop signage + exit ramp markers ─────────────────────────────
  // For each rest stop drop a sign sprite at −5 mi and −1 mi plus the
  // exit-ramp marker at the stop itself. Spread each sign across a small
  // segment range so the player gets multiple chances to see it as the
  // road scrolls — a single one-segment sprite was too easy to miss in
  // tree clutter.
  //
  // ALSO: tag a 0.25-mile-wide window of segments leading into the stop
  // with a `rampStrength` value (0 → 1 as the player nears the stop). This
  // drives Road.js's exit-ramp painting so the asphalt visibly tapers off
  // to the right just like a real off-ramp.
  // Match the trigger window (1.0 mi before stop, 0.3 mi after) so the
  // painted ramp covers EVERY segment where the player can take the exit
  // — no dead zones where the rest-stop window is open but the asphalt
  // hasn't been painted yet.
  const RAMP_WINDOW_SEG = Math.floor(1.0 / TOTAL_ROUTE_MILES * count); // ≈1442 segs ≈ 1 mi
  // ── Real mileage signs at every checkpoint ──────────────────────────
  // For each location in CHECKPOINTS (every named town/landmark in the
  // route), drop a green I-90-style location sign 1 mile before the
  // location's start mile.  Replaces the random brown signs that used
  // to clutter the shoulder.  (SEGS_PER_MILE is already declared above
  // for the random-cop placement loop.)
  for (const cp of CHECKPOINTS) {
    if (cp.isStart) continue;                       // skip "West Seattle" — it IS the start
    // Skip checkpoints that share their mile with a REST_STOP — the
    // rest-stop signage suite (5mi advance, exit sign, amenities placard)
    // already labels that location, so a mileage_sign painted at cp.mileage-1
    // would overlap the exit_sign_green at rs.mileage-1 and double the text.
    const sharesWithRestStop = REST_STOPS.some(rs => Math.abs(rs.mileage - cp.mileage) < 1.5);
    if (sharesWithRestStop) continue;
    const advanceMile = Math.max(0, cp.mileage - 1);
    const segIdx = Math.floor(advanceMile * SEGS_PER_MILE) % count;
    if (segIdx < 0 || segIdx >= count) continue;
    segments[segIdx].sprites.push({
      type:      'mileage_sign',
      townName:  cp.name,
      mileage:   cp.mileage,
      offset:    1.20,
      baseW: 5200, baseH: 6700,                     // bigger so EXIT N + town fit
      collected: false,
    });
  }

  // Helper — clear right-side scenery (trees, buildings, etc.) from a
  // window of segments around a sign placement so the sign is never
  // visually blocked.  Span is in segments; default ≈ 0.05 mi before and
  // 0.10 mi after — enough that the player has a clear approach view.
  const clearRightSceneryAround = (centerSeg, before = 80, after = 140) => {
    for (let k = -before; k <= after; k++) {
      const idx = ((centerSeg + k) % count + count) % count;
      const seg = segments[idx];
      if (!seg?.sprites) continue;
      seg.sprites = seg.sprites.filter(sp => {
        if (sp.type === 'rest_sign') return true;
        if (sp.type === 'exit_sign_green') return true;
        if (sp.type === 'amenities_sign') return true;
        if (sp.type === 'mileage_sign') return true;
        if (sp.type === 'grade_sign') return true;
        if (sp.type === 'next_stops_sign') return true;
        if (sp.isCollectible)         return true;
        const off = sp.offset ?? 0;
        if (off > 1.0 && off < 3.5)   return false;     // strip right-side scenery
        return true;
      });
    }
  };

  // ── Steep-grade warning signs ─────────────────────────────────────────
  // Real I-90 has yellow regulatory signs ahead of the major sustained
  // grades.  Spawn them just before the top of each big climb/descent so
  // the player gets the same visual cue trucks do.
  const GRADE_SIGNS = [
    // Eastbound descent off Snoqualmie summit (mi 52→62, ~3-4% sustained)
    { mile: 51,  line1: 'TRUCKS USE',   line2: 'LOWER GEAR' },
    { mile: 53,  line1: '6% GRADE',     line2: 'NEXT 10 MI' },
    // Ryegrass Summit drop into Vantage (mi 122→132, the route's most
    // dramatic descent — 1965 ft drop in 10 mi, 4-5% in places).
    { mile: 121, line1: 'STEEP GRADE',  line2: 'NEXT 10 MI' },
    { mile: 123, line1: 'TRUCKS USE',   line2: 'LOWER GEAR' },
    // Westbound climb up Snoqualmie (32→52, 2497 ft over 20 mi)
    { mile: 33,  line1: 'STEEP CLIMB',  line2: 'CHAIN-UP AHEAD' },
    // Snow-zone warnings ahead of the white-out (Phase 3 weather)
    { mile: 38,  line1: 'CHAINS',       line2: 'REQUIRED' },
    { mile: 39,  line1: 'TRACTION',     line2: 'TIRES ADVISED' },
    // Climb out of Vantage (132→140)
    { mile: 133, line1: '6% GRADE',     line2: 'NEXT 8 MI' },
  ];
  for (const gs of GRADE_SIGNS) {
    const segIdx = Math.floor(gs.mile * SEGS_PER_MILE) % count;
    if (segIdx < 0 || segIdx >= count) continue;
    segments[segIdx].sprites.push({
      type:    'grade_sign',
      line1:   gs.line1,
      line2:   gs.line2,
      offset:  1.18,
      baseW:   2800, baseH: 3400,
      collected: false,
    });
    clearRightSceneryAround(segIdx, 60, 100);
  }

  // Apply to the mileage signs (CHECKPOINT name signs) we just placed.
  // Skip checkpoints that share their mile with a REST_STOP — those
  // weren't given a mileage_sign in the loop above, so there's nothing
  // to clear scenery around.
  for (const cp of CHECKPOINTS) {
    if (cp.isStart) continue;
    if (REST_STOPS.some(rs => Math.abs(rs.mileage - cp.mileage) < 1.5)) continue;
    const advanceMile = Math.max(0, cp.mileage - 1);
    const segIdx = Math.floor(advanceMile * SEGS_PER_MILE) % count;
    clearRightSceneryAround(segIdx);
  }

  for (const rs of REST_STOPS) {
    const segAt = (mi) => Math.floor((mi / TOTAL_ROUTE_MILES) * count) % count;
    const placeSign = (centerSeg, sub) => {
      // Single-segment placement (no 4-copy stack — caused overlapping
      // ghosts at different perspective scales).
      const segIdx = ((centerSeg % count) + count) % count;
      segments[segIdx].sprites.push({
        type:      'rest_sign',
        sub,                                   // '5mi' | '1mi' | 'exit'
        stopId:    rs.id,
        offset:    1.18,
        baseW: 4200, baseH: 5800,              // bumped — bigger rest-stop sign
        collected: false,
      });
    };
    placeSign(segAt(rs.mileage - 5), '5mi');
    placeSign(segAt(rs.mileage),     'exit');
    // Clear approach scenery around each rest-stop sign so trees/buildings
    // can't hide them.  The exit-window sign falls within the ramp clear
    // band; the −5mi advance sign and the new −1mi green exit sign +
    // −0.75mi amenities preview both sit outside it.
    clearRightSceneryAround(segAt(rs.mileage - 5));
    clearRightSceneryAround(segAt(rs.mileage - 1));      // green sign lives here
    clearRightSceneryAround(segAt(rs.mileage - 0.75));   // amenities placard

    // Big green I-90-style overhead exit sign 1 mi before the stop. The
    // sign reads EXIT <label> + town and now carries the highway shield
    // badge in the top-left corner (composited by GameScene).  Single-
    // segment placement (multiple copies stacked = ghost effect).
    // GUARD: if the −1 mi spot is on a bridge / in a tunnel / over water,
    // walk forward to the next dry segment so the sign isn't planted in
    // the lake or through tunnel walls.
    const findDrySeg = (startSegIdx, maxSearch = 400) => {
      for (let k = 0; k < maxSearch; k++) {
        const idx = (startSegIdx + k) % count;
        const seg = segments[idx];
        if (seg && !seg.bridge && !seg.tunnel && !seg.water) return idx;
      }
      return startSegIdx;
    };
    const greenSegIdx = findDrySeg(((segAt(Math.max(0, rs.mileage - 1)) % count) + count) % count);
    segments[greenSegIdx].sprites.push({
      type:      'exit_sign_green',
      sub:       'green',
      stopId:    rs.id,
      exitLabel: rs.exit ?? `Mile ${rs.mileage}`,   // "Exit 7B", "WA-262", etc.
      mileage:   rs.mileage,
      townName:  rs.name.split(',')[0],             // strip ", WA"
      hwyKey:    rs.hwy ?? 'hwy_i90',               // shield badge texture
      offset:    1.20,
      baseW: 4800, baseH: 6600,                     // bumped — big I-90 overhead sign
      collected: false,
    });

    // Amenities preview placard 0.75 mi before the stop (¼ mi after the
    // exit sign).  Sized to match exit_sign_green so the placard is held
    // up off the ground by tall steel legs (face occupies the upper ~62 %
    // of the sprite area, legs reach down to the road surface).  The
    // pre-baked PNG is overlaid by GameScene._renderSignDecals at the
    // PNG's natural 1277:840 aspect, centered inside the white frame
    // painted by Road.js's case 'amenities_sign'.
    const amenSegIdx = findDrySeg(((segAt(Math.max(0, rs.mileage - 0.75)) % count) + count) % count);
    segments[amenSegIdx].sprites.push({
      type:       'amenities_sign',
      stopId:     rs.id,
      amenities:  rs.amenities ?? [],
      signKey:    `sign_${rs.id}`,                   // pre-baked PNG key
      offset:     1.20,
      baseW: 4800, baseH: 6600,                       // match exit_sign_green
      collected:  false,
    });

    // Paint the actual exit ramp.  rampStrength ramps 0 → 1 over the last
    // RAMP_WINDOW segments; Road.js reads it to widen the right shoulder
    // and draw a tapered "off-ramp" trapezoid.
    //
    // GUARD: skip any segment flagged bridge / tunnel / water so the ramp
    // is never painted out over a lake or through tunnel walls.  When the
    // window crosses a bridge (e.g. Mercer Island after the LV Murrow,
    // Bellevue after the East Channel) we re-base `t` so the ramp grows
    // from 0 at the first DRY segment up to 1 at the exit point — that
    // way the off-ramp opens cleanly off the bridge without an abrupt
    // mid-window pop-in.
    const exitSeg = segAt(rs.mileage);
    const isWet = (s) => !!(s?.bridge || s?.tunnel || s?.water);
    let dryStart = 0;
    for (let k = 0; k < RAMP_WINDOW_SEG; k++) {
      const segIdx = (exitSeg - RAMP_WINDOW_SEG + 1 + k + count) % count;
      if (!isWet(segments[segIdx])) { dryStart = k; break; }
    }
    const dryRange = Math.max(1, RAMP_WINDOW_SEG - dryStart);
    for (let k = dryStart; k < RAMP_WINDOW_SEG; k++) {
      const segIdx = (exitSeg - RAMP_WINDOW_SEG + 1 + k + count) % count;
      const seg = segments[segIdx];
      if (!seg) continue;
      if (isWet(seg)) continue;                  // never paint over water/bridge/tunnel
      const t = (k - dryStart) / dryRange;       // 0 (first dry seg) → 1 (at exit)
      seg.rampStrength = Math.max(seg.rampStrength ?? 0, t);
      seg.rampStopId   = rs.id;
    }
    // After-exit window — extend to 0.3 mi to match the trigger window's
    // winAfter so the ramp is paved for the player's whole pull-over zone.
    const AFTER_SEGS = Math.floor(0.3 / TOTAL_ROUTE_MILES * count);
    for (let k = 1; k < AFTER_SEGS; k++) {
      const segIdx = (exitSeg + k) % count;
      const seg = segments[segIdx];
      if (!seg) continue;
      if (isWet(seg)) continue;                  // same guard on the after-window
      seg.rampStrength = Math.max(seg.rampStrength ?? 0, 1 - k / AFTER_SEGS);
      seg.rampStopId   = rs.id;
    }
    // Clear the right-shoulder scenery (trees, buildings, sign clutter)
    // off every ramp-tagged segment.  The ramp asphalt extends out to
    // ~x=2.4 lane units; anything spawned with positive offset > 1.0 is
    // sitting on or alongside the ramp and would block the pull-over.
    // Left-side scenery is preserved.
    const rampWindowFull = RAMP_WINDOW_SEG + AFTER_SEGS;
    for (let k = 0; k < rampWindowFull; k++) {
      const segIdx = (exitSeg - RAMP_WINDOW_SEG + 1 + k + count) % count;
      const seg = segments[segIdx];
      if (!seg?.sprites) continue;
      seg.sprites = seg.sprites.filter(sp => {
        // Always keep rest-stop signs and gameplay collectibles regardless of side.
        if (sp.type === 'rest_sign') return true;
        if (sp.type === 'exit_sign_green') return true;
        if (sp.type === 'amenities_sign') return true;
        if (sp.type === 'next_stops_sign') return true;
        if (sp.isCollectible)        return true;
        // Strip right-side scenery only within the ramp band (offset
        // 1.0–3.5).  Outer-band trees / buildings beyond x=3.5 stay so
        // the horizon still reads as populated.
        const off = sp.offset ?? 0;
        if (off > 1.0 && off < 3.5) return false;
        return true;
      });
    }
  }

  // ── "Next exits" placards every 10 miles ──────────────────────────────
  // Tall green sign listing the next 3 upcoming rest stops + their mile
  // counts.  Placed 10 mi past Seattle through to the last rest stop, but
  // skipped if too close to an existing exit/amenities placard (those
  // already advertise the next stop) and skipped if the segment is on
  // a bridge or in a tunnel.
  const NEXT_STOPS_INTERVAL_MI = 10;
  const NEXT_STOPS_AVOID_MI    = 1.2;   // skip if within 1.2 mi of any rest stop
  for (let mi = NEXT_STOPS_INTERVAL_MI; mi < TOTAL_ROUTE_MILES - 5; mi += NEXT_STOPS_INTERVAL_MI) {
    // Skip if too close to a rest-stop sign zone (those already preview the next exit).
    const tooClose = REST_STOPS.some(rs => Math.abs(rs.mileage - mi) < NEXT_STOPS_AVOID_MI);
    if (tooClose) continue;
    const segIdx = Math.floor((mi / TOTAL_ROUTE_MILES) * count) % count;
    const seg    = segments[segIdx];
    if (!seg) continue;
    if (seg.bridge || seg.tunnel || seg.water) continue;
    // Build the next-3-stops list (deduped, only stops AHEAD of this mile).
    const upcoming = REST_STOPS
      .filter(rs => rs.mileage > mi)
      .slice(0, 3)
      .map(rs => ({ name: rs.name.split(',')[0], mi: Math.round(rs.mileage - mi) }));
    if (upcoming.length === 0) continue;
    seg.sprites.push({
      type:      'next_stops_sign',
      rows:      upcoming,
      offset:    1.18,
      baseW: 4400, baseH: 6200,
      collected: false,
    });
    clearRightSceneryAround(segIdx, 70, 120);
  }

  // ── Landmark: Space Needle ─────────────────────────────────────────
  // Real geography: driving I-90 east, the Space Needle is north (LEFT)
  // of the highway, visible just past the floating-bridge approach.
  // Place at mile 7.5 — just east of the Mt Baker tunnel exit (mile 7)
  // on the LEFT shoulder so it stands beside the bridge approach.
  // baseW/H ratio matches the source PNG (1:1, 2500×2500) and is
  // stretched taller by _renderSceneSprites's landmark size multiplier.
  const needleSeg = Math.floor((7.5 / TOTAL_ROUTE_MILES) * count) % count;
  segments[needleSeg].sprites.push({
    type:      'landmark',
    texKey:    'space_needle',
    offset:    -1.6,               // LEFT side of the road (north of I-90)
    baseW:     2500, baseH: 2500,
    collected: false,
  });

  return segments;
}

/**
 * Weapon drop table — split evenly between forward-firing and rear-facing
 * tools so the player can defend both sides at roughly the same rate.
 *
 *   Forward (kills front cops):  gun, rocket   → 50% combined
 *   Backward (kills rear cops):  spike, paint  → 50% combined
 *
 * Rockets are bidirectional in CopSystem.useF12Token so the rocket pickup
 * itself counts toward "balanced" because the player chooses direction at
 * fire time via the weapon-cycle button.
 */
function pickF12(rng) {
  const r = rng.next();
  if (r < 0.30) return 'f12_gun';     // 30% — forward
  if (r < 0.50) return 'f12_rocket';  // 20% — bidirectional (player picks)
  if (r < 0.75) return 'f12_spike';   // 25% — backward
  return 'f12_paint';                  // 25% — backward
}

function pickCollectible(rng, routeProgress) {
  if (routeProgress < 0.25) return rng.bool(0.7) ? 'beer' : 'weed';
  if (routeProgress < 0.45) return rng.pick(['beer', 'beer', 'weed', 'cocaine']);
  return rng.pick(['beer', 'weed', 'cocaine', 'beer', 'weed']);
}
